version: 2
updates:
  - package-ecosystem: nuget
    directory: /
    schedule: { interval: weekly }
    commit-message:
      prefix: "chore"
      include: "scope"
    groups:
      dotnet-minor-patch:
        applies-to: version-updates
        patterns: ["*"]
        update-types: [minor, patch]
      dotnet-security:
        applies-to: security-updates
        patterns: ["*"]
        update-types: [minor, patch]
  - package-ecosystem: bun
    directory: /
    schedule: { interval: weekly }
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"
    groups:
      nx-minor-patch:
        applies-to: version-updates
        patterns: ["nx", "@nx/*"]
        update-types: [minor, patch]
      bun-minor-patch:
        applies-to: version-updates
        patterns: ["*"]
        exclude-patterns: ["nx", "@nx/*"]
        update-types: [minor, patch]
      bun-security:
        applies-to: security-updates
        patterns: ["*"]
        update-types: [minor, patch]
  - package-ecosystem: docker
    directory: /deploy
    schedule: { interval: weekly }
    commit-message:
      prefix: "chore"
      include: "scope"
    groups:
      docker-minor-patch:
        applies-to: version-updates
        patterns: ["*"]
        update-types: [minor, patch]
  - package-ecosystem: github-actions
    directory: /
    schedule: { interval: weekly }
    commit-message:
      prefix: "chore"
      include: "scope"
    groups:
      actions-minor-patch:
        applies-to: version-updates
        patterns: ["*"]
        update-types: [minor, patch]
