<Project>
  <Import Project="$([MSBuild]::GetPathOfFileAbove('Directory.Build.props', '$(MSBuildThisFileDirectory)../'))" />

  <PropertyGroup>
    <IsTestProject>true</IsTestProject>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <AnalysisLevel>latest-All</AnalysisLevel>
    <AnalysisMode>All</AnalysisMode>
    <AnalysisModeGlobalization>None</AnalysisModeGlobalization>
    <AnalysisModeSecurity>All</AnalysisModeSecurity>
    <RunAnalyzersDuringBuild>true</RunAnalyzersDuringBuild>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    <CodeAnalysisTreatWarningsAsErrors>false</CodeAnalysisTreatWarningsAsErrors>
    <NoWarn>CS1587;CS1591;CS1998;CA1707;CA1014;CA1515;CA1051;CA1310;CA1852;CA1716;CA1711;CA1816;CA2213;IDE0005</NoWarn>
  </PropertyGroup>
</Project>
