<Project>
  <Import Project="$([MSBuild]::GetPathOfFileAbove('Directory.Build.props', '$(MSBuildThisFileDirectory)../'))" />

  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsPublishable>true</IsPublishable>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <IsTrimmable>false</IsTrimmable>
    <EnableTrimAnalyzer>false</EnableTrimAnalyzer>
    <Version>0.0.1</Version>
    <FileVersion>0.0.1</FileVersion>
    <AssemblyVersion>0.0.1</AssemblyVersion>
  </PropertyGroup>
</Project>
