// <auto-generated />
using Customers.Application.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Customers.Host.Database.Migrations;

[DbContext(typeof(CustomerDbContext))]
partial class CustomerDbContextModelSnapshot : ModelSnapshot
{
    /// <inheritdoc />
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "10.0.7")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("Customers.Domain.Entities.Tenant", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<DateTimeOffset>("CreatedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("CreatedBy")
                    .HasColumnType("text");

                b.Property<string>("DatabaseProvider")
                    .IsRequired()
                    .HasMaxLength(64)
                    .HasColumnType("character varying(64)");

                b.Property<string>("DatabaseStrategy")
                    .IsRequired()
                    .HasMaxLength(64)
                    .HasColumnType("character varying(64)");

                b.Property<string>("DeletedBy")
                    .HasColumnType("text");

                b.Property<DateTimeOffset?>("DeletedOn")
                    .HasColumnType("timestamp with time zone");

                b.Property<bool>("HasReadReplicas")
                    .HasColumnType("boolean");

                b.Property<string>("Identifier")
                    .IsRequired()
                    .HasMaxLength(128)
                    .HasColumnType("character varying(128)");

                b.Property<bool>("IsDeleted")
                    .HasColumnType("boolean");

                b.Property<string>("Status")
                    .IsRequired()
                    .HasMaxLength(32)
                    .HasColumnType("character varying(32)");

                b.Property<string>("UpdatedBy")
                    .HasColumnType("text");

                b.Property<DateTimeOffset?>("UpdatedOn")
                    .HasColumnType("timestamp with time zone");

                b.HasKey("Id");

                b.HasIndex("Identifier")
                    .IsUnique();

                b.ToTable("tenants", (string)null);
            });
#pragma warning restore 612, 618
    }
}
