<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SharedKernel.Core\SharedKernel.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MemoryPack" />
  </ItemGroup>

</Project>
