// <auto-generated />
using System;
using Catalog.Application.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Catalog.Host.Database.Migrations
{
    [DbContext(typeof(CatalogDbContext))]
    partial class CatalogDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Catalog.Domain.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("DeletedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("UpdatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Slug");

                    b.ToTable("Categories", (string)null);
                });

            modelBuilder.Entity("Catalog.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("DeletedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("UpdatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Products", (string)null);
                });

            modelBuilder.Entity("Catalog.Domain.Entities.Supplier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("ContactPhone")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("DeletedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("UpdatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Suppliers", (string)null);
                });

            modelBuilder.Entity("Catalog.Domain.Entities.Product", b =>
                {
                    b.OwnsMany("Catalog.Domain.Entities.Variant", "Variants", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset>("CreatedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("CreatedBy")
                                .HasColumnType("text");

                            b1.Property<string>("DeletedBy")
                                .HasColumnType("text");

                            b1.Property<DateTimeOffset?>("DeletedOn")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<bool>("IsActive")
                                .HasColumnType("boolean");

                            b1.Property<bool>("IsDefault")
                                .HasColumnType("boolean");

                            b1.Property<bool>("IsDeleted")
                                .HasColumnType("boolean");

                            b1.Property<Guid>("ProductId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Sku")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)");

                            b1.Property<string>("UpdatedBy")
                                .HasColumnType("text");

                            b1.Property<DateTimeOffset?>("UpdatedOn")
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("Id");

                            b1.HasIndex("ProductId");

                            b1.ToTable("Variants", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ProductId");

                            b1.OwnsOne("Catalog.Domain.ValueObjects.Money", "SellPrice", b2 =>
                                {
                                    b2.Property<Guid>("VariantId")
                                        .HasColumnType("uuid");

                                    b2.Property<decimal>("Amount")
                                        .HasPrecision(18, 2)
                                        .HasColumnType("numeric(18,2)")
                                        .HasColumnName("SellPriceAmount");

                                    b2.Property<string>("Currency")
                                        .IsRequired()
                                        .HasMaxLength(3)
                                        .HasColumnType("character varying(3)")
                                        .HasColumnName("SellPriceCurrency");

                                    b2.HasKey("VariantId");

                                    b2.ToTable("Variants");

                                    b2.WithOwner()
                                        .HasForeignKey("VariantId");
                                });

                            b1.OwnsMany("Catalog.Domain.Entities.VariantSupplier", "Suppliers", b2 =>
                                {
                                    b2.Property<Guid>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("uuid");

                                    b2.Property<DateTimeOffset>("CreatedAt")
                                        .HasColumnType("timestamp with time zone");

                                    b2.Property<string>("CreatedBy")
                                        .HasColumnType("text");

                                    b2.Property<string>("DeletedBy")
                                        .HasColumnType("text");

                                    b2.Property<DateTimeOffset?>("DeletedOn")
                                        .HasColumnType("timestamp with time zone");

                                    b2.Property<bool>("IsDeleted")
                                        .HasColumnType("boolean");

                                    b2.Property<bool>("IsPreferred")
                                        .HasColumnType("boolean");

                                    b2.Property<int>("LeadTimeDays")
                                        .HasColumnType("integer");

                                    b2.Property<int>("MinOrderQuantity")
                                        .HasColumnType("integer");

                                    b2.Property<Guid>("SupplierId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("SupplierSku")
                                        .IsRequired()
                                        .HasMaxLength(128)
                                        .HasColumnType("character varying(128)");

                                    b2.Property<string>("UpdatedBy")
                                        .HasColumnType("text");

                                    b2.Property<DateTimeOffset?>("UpdatedOn")
                                        .HasColumnType("timestamp with time zone");

                                    b2.Property<Guid>("VariantId")
                                        .HasColumnType("uuid");

                                    b2.HasKey("Id");

                                    b2.HasIndex("VariantId");

                                    b2.ToTable("VariantSuppliers", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("VariantId");

                                    b2.OwnsMany("Catalog.Domain.Entities.SupplierPriceHistory", "PriceHistory", b3 =>
                                        {
                                            b3.Property<Guid>("Id")
                                                .ValueGeneratedOnAdd()
                                                .HasColumnType("uuid");

                                            b3.Property<DateTimeOffset>("CreatedAt")
                                                .HasColumnType("timestamp with time zone");

                                            b3.Property<string>("CreatedBy")
                                                .HasColumnType("text");

                                            b3.Property<string>("DeletedBy")
                                                .HasColumnType("text");

                                            b3.Property<DateTimeOffset?>("DeletedOn")
                                                .HasColumnType("timestamp with time zone");

                                            b3.Property<DateTimeOffset>("EffectiveFrom")
                                                .HasColumnType("timestamp with time zone");

                                            b3.Property<bool>("IsDeleted")
                                                .HasColumnType("boolean");

                                            b3.Property<string>("UpdatedBy")
                                                .HasColumnType("text");

                                            b3.Property<DateTimeOffset?>("UpdatedOn")
                                                .HasColumnType("timestamp with time zone");

                                            b3.Property<Guid>("VariantSupplierId")
                                                .HasColumnType("uuid");

                                            b3.HasKey("Id");

                                            b3.HasIndex("VariantSupplierId");

                                            b3.ToTable("SupplierPriceHistory", (string)null);

                                            b3.WithOwner()
                                                .HasForeignKey("VariantSupplierId");

                                            b3.OwnsOne("Catalog.Domain.ValueObjects.Money", "CostPrice", b4 =>
                                                {
                                                    b4.Property<Guid>("SupplierPriceHistoryId")
                                                        .HasColumnType("uuid");

                                                    b4.Property<decimal>("Amount")
                                                        .HasPrecision(18, 2)
                                                        .HasColumnType("numeric(18,2)")
                                                        .HasColumnName("CostPriceAmount");

                                                    b4.Property<string>("Currency")
                                                        .IsRequired()
                                                        .HasMaxLength(3)
                                                        .HasColumnType("character varying(3)")
                                                        .HasColumnName("CostPriceCurrency");

                                                    b4.HasKey("SupplierPriceHistoryId");

                                                    b4.ToTable("SupplierPriceHistory");

                                                    b4.WithOwner()
                                                        .HasForeignKey("SupplierPriceHistoryId");
                                                });

                                            b3.Navigation("CostPrice")
                                                .IsRequired();
                                        });

                                    b2.OwnsOne("Catalog.Domain.ValueObjects.Money", "CostPrice", b3 =>
                                        {
                                            b3.Property<Guid>("VariantSupplierId")
                                                .HasColumnType("uuid");

                                            b3.Property<decimal>("Amount")
                                                .HasPrecision(18, 2)
                                                .HasColumnType("numeric(18,2)")
                                                .HasColumnName("CostPriceAmount");

                                            b3.Property<string>("Currency")
                                                .IsRequired()
                                                .HasMaxLength(3)
                                                .HasColumnType("character varying(3)")
                                                .HasColumnName("CostPriceCurrency");

                                            b3.HasKey("VariantSupplierId");

                                            b3.ToTable("VariantSuppliers");

                                            b3.WithOwner()
                                                .HasForeignKey("VariantSupplierId");
                                        });

                                    b2.Navigation("CostPrice")
                                        .IsRequired();

                                    b2.Navigation("PriceHistory");
                                });

                            b1.OwnsMany("Catalog.Domain.ValueObjects.VariantAttribute", "Attributes", b2 =>
                                {
                                    b2.Property<Guid>("VariantId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("Name")
                                        .HasMaxLength(128)
                                        .HasColumnType("character varying(128)");

                                    b2.Property<string>("Value")
                                        .IsRequired()
                                        .HasMaxLength(512)
                                        .HasColumnType("character varying(512)");

                                    b2.HasKey("VariantId", "Name");

                                    b2.ToTable("VariantAttributes", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("VariantId");
                                });

                            b1.Navigation("Attributes");

                            b1.Navigation("SellPrice")
                                .IsRequired();

                            b1.Navigation("Suppliers");
                        });

                    b.Navigation("Variants");
                });
#pragma warning restore 612, 618
        }
    }
}
