<Project Sdk="Microsoft.NET.Sdk">
  <Sdk Name="Aspire.AppHost.Sdk" Version="13.4.6" />
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsAspireHost>true</IsAspireHost>
    <UserSecretsId>teck-apphost</UserSecretsId>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.AppHost" />
    <PackageReference Include="Aspire.Hosting.PostgreSQL" />
    <PackageReference Include="Aspire.Hosting.RabbitMQ" />
    <PackageReference Include="Aspire.Hosting.Redis" />
    <PackageReference Include="Aspire.Hosting.Keycloak" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\services\commerce\order\Order.Host\Order.Host.csproj" />
    <ProjectReference Include="..\..\services\commerce\basket\Basket.Host\Basket.Host.csproj" />
    <ProjectReference Include="..\..\services\commerce\inventory\Inventory.Host\Inventory.Host.csproj" />
    <ProjectReference Include="..\..\services\commerce\customer\Customer.Host\Customer.Host.csproj" />
    <ProjectReference Include="..\..\services\commerce\catalog\Catalog.Host\Catalog.Host.csproj" />
    <ProjectReference Include="..\..\services\gateway\public\Gateway.Public.csproj" />
  </ItemGroup>
</Project>
