<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>Gateway.Public</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="FastEndpoints.Messaging.Remote" />
    <PackageReference Include="Keycloak.AuthServices.Authentication" />
    <PackageReference Include="MessagePack" />
    <PackageReference Include="Microsoft.Extensions.ServiceDiscovery" />
    <PackageReference Include="Microsoft.Extensions.ServiceDiscovery.Yarp" />
    <PackageReference Include="Polly" />
    <PackageReference Include="Treyt.Yarp.ReverseProxy.Swagger" />
    <PackageReference Include="Yarp.ReverseProxy" />
    <PackageReference Include="ZiggyCreatures.FusionCache" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\aspire\Teck.ServiceDefaults\Teck.ServiceDefaults.csproj" />
    <ProjectReference Include="..\..\..\shared\SharedKernel.Core\SharedKernel.Core.csproj" />
    <ProjectReference Include="..\..\..\shared\SharedKernel.Grpc.Contracts\SharedKernel.Grpc.Contracts.csproj" />
    <ProjectReference Include="..\..\..\shared\SharedKernel.Infrastructure\SharedKernel.Infrastructure.csproj" />
  </ItemGroup>
</Project>
