<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>Teck.LocalIdentity</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\services\commerce\customer\Customer.Application\Customer.Application.csproj" />
    <ProjectReference Include="..\..\services\commerce\customer\Customer.Domain\Customer.Domain.csproj" />
  </ItemGroup>
</Project>
